[package]
name = "charts"
version = "0.1.0"
edition = "2021"

[dependencies]
charts-rs = { version = "0.3.19", features = ["image-encoder"]}
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.134"
