[package]
name = "charts"
version = "0.1.0"
edition = "2021"

[dependencies]
charts-rs = { version = "0.3.20", features = ["image-encoder"]}
clap = { version = "4.5.31", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.139"
